version: '3'
services:
  backend:
    image: backend-image:latest
    environment:
      - CORS_ALLOWLIST=$CORS_ALLOWLIST
    networks:
      - frontend
    ports:
      - "5000:5000"  
 
  frontend:
    image: frontend:latest
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "8080:80"
    networks:
      - frontend
 
networks:
  frontend:
    driver: bridge
    internal: false